# Generated by Django 3.2.9 on 2022-10-31 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isLeader', models.BooleanField(default=0)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('phoneNumber', models.TextField(blank=True)),
                ('gender', models.CharField(max_length=10)),
                ('team', models.CharField(max_length=124)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamName', models.CharField(max_length=124, unique=True)),
                ('city', models.CharField(max_length=50)),
                ('referralCode', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='RollNumbers',
        ),
        migrations.AddField(
            model_name='member',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.team'),
        ),
    ]
