# Generated by Django 3.2.9 on 2022-10-31 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20221031_1730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='referralCode',
            new_name='referalCode',
        ),
    ]
