# Generated by Django 3.2.9 on 2022-10-31 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_referralcode_team_referalcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='isLeader',
            field=models.BooleanField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.team'),
        ),
        migrations.AlterField(
            model_name='member',
            name='phoneNumber',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='team',
            field=models.CharField(max_length=124, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='referalCode',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='teamName',
            field=models.CharField(max_length=124, null=True, unique=True),
        ),
    ]
