# Generated by Django 3.2.9 on 2022-10-31 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20221031_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='member',
            name='team',
            field=models.ForeignKey(max_length=124, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.team'),
        ),
    ]
