# Generated by Django 3.2.9 on 2022-11-05 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_member_college'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='college',
        ),
    ]
