# Generated by Django 3.2.9 on 2022-12-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_member_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='previousPerformance',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
