# Generated by Django 4.0.4 on 2022-12-11 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20221210_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='referalCode',
        ),
    ]
