# Generated by Django 4.2.3 on 2024-10-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0013_remove_team_referalcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="is_phone_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="team",
            name="otp",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
