# Generated by Django 5.1.2 on 2024-10-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0014_team_is_phone_verified_team_otp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="is_phone_verified",
        ),
        migrations.AddField(
            model_name="team",
            name="otp_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="team",
            name="registration_succesful",
            field=models.BooleanField(default=False),
        ),
    ]
