# Generated by Django 5.1.2 on 2024-11-03 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0015_remove_team_is_phone_verified_team_otp_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
