# Generated by Django 5.1.2 on 2024-12-23 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0016_alter_team_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="team",
            old_name="registration_succesful",
            new_name="registration_successful",
        ),
    ]
