# Generated by Django 5.1.2 on 2024-12-24 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0017_rename_registration_succesful_team_registration_successful"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="otp",
        ),
        migrations.RemoveField(
            model_name="team",
            name="otp_created_at",
        ),
    ]
